name: Builder

env:
  BUILD_ARGS: "--test"
  MONITORED_FILES: "build.yaml config.yaml build.json config.json Dockerfile rootfs"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    outputs:
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.2

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - run: |
          declare -a changed
          for file in ${{ env.MONITORED_FILES }}; do
            if [[ -n ${changed} ]]; then
              break
            fi

            if [[ "${{ steps.changed_files.outputs.all }}" =~ $file ]]; then
              changed=true
            fi
          done

          if [[ -n ${changed} ]]; then
            echo "A monitored file changed.";
            echo "::set-output name=changed::true";
          else
            echo "No monitored files changed.";
          fi
  build:
    needs: init
    runs-on: ubuntu-latest
    if: needs.init.outputs.changed == 'true'
    name: Build add-on
    strategy:
      matrix:
        arch: ["amd64", "armv7", "aarch64"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.2

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./"

      - name: Check if add-on should be built
        id: check
        run: |
          if [[ "${{ steps.info.outputs.architectures }}" =~ ${{ matrix.arch }} ]]; then
             echo "::set-output name=build_arch::true";
             echo "::set-output name=image::$(echo ${{ steps.info.outputs.image }} | cut -d'/' -f3)";
             if [[ -z "${{ github.head_ref }}" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
                 echo "BUILD_ARGS=" >> $GITHUB_ENV;
             fi
           else
             echo "${{ matrix.arch }} is not a valid arch for this add-on, skipping build";
             echo "::set-output name=build_arch::false";
          fi

      - name: Login to GitHub Container Registry
        if: env.BUILD_ARGS != '--test'
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build add-on
        if: steps.check.outputs.build_arch == 'true'
        uses: home-assistant/builder@master
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            --${{ matrix.arch }} \
            --target /data/${GITHUB_REPOSITORY##*/} \
            --image "${{ steps.check.outputs.image }}" \
            --addon
