on:
  workflow_dispatch:
    inputs:
      semverIncrement:
        description: Increment major/minor/patch using values of m/i/p
        required: true
        default: i

name: Releaser

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ghostfolio
      - name: Get latest release
        run: |
          echo "latest_release=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --silent https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | jq -r .tag_name | sed s/v// )" >> $GITHUB_ENV
      - name: Increment semver
        id: semver
        uses: matt-FFFFFF/simple-semver@v0.1.1
        with:
          semver-input: ${{ env.latest_release }}
          increment: ${{ github.event.inputs.semverIncrement }}
      - name: Create tag
        run: |
          git config --global user.email "actions.no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git tag -a v${{ steps.semver.outputs.semver }} -m 'Release automation'
          git push --tags
        working-directory: ${{ github.workspace }}/ghostfolio
      - name: Create release
        uses: softprops/action-gh-release@v2.0.4
        with:
          tag_name: v${{ steps.semver.outputs.semver }}
          generate_release_notes: true
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout addon repo
        uses: actions/checkout@v4.1.2
        with:
          path: repo
          repository: lildude/ha-addons
          token: ${{ secrets.ADDON_REPO_PAT }}
      - name: Update addon repo
        run: |
          cp -vf ${{ github.workspace }}/ghostfolio/*.png ${{ github.workspace }}/repo/ghostfolio
          cp -vf ${{ github.workspace }}/ghostfolio/*.md ${{ github.workspace }}/repo/ghostfolio
          jq '.version="${{ steps.semver.outputs.semver }}"' < ${{ github.workspace }}/ghostfolio/config.json > ${{ github.workspace }}/repo/ghostfolio/config.json
      - name: Add changes to addon repo
        run: |
          if [ "$(git status -s)" ]; then
            git add .
            git commit -m 'Update ha-addon-ghostfolio to v${{ steps.semver.outputs.semver }}'
            git push
          fi
        working-directory: ${{ github.workspace }}/repo/ghostfolio